services:
#  aston-ht-2:
#    build:
#      dockerfile: Dockerfile
#    image: aston_ht_image
#    container_name: astonht
#    ports:
#      - "8080:8080"
#    depends_on:
#      - aston-ht-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://astondb:5432/stats-db
#      - POSTGRES_DB=aston-db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=iamroot

  aston-ht-db:
    image: postgres:14-alpine
    container_name: aston-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=astondb-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot