services:
  astondb:
    image: postgres:14-alpine
    container_name: aston
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=astondb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot