drop table if exists student;
drop table if exists meeting;
drop table if exists presence;
drop table if exists meeting_to_presence;

create table if not exists student(
    id bigint primary key generated by default as identity,
    name varchar(255),
    skype varchar(255),
    telegram varchar(255),
    github varchar(255),
    bot integer,
    isActive varchar(255)
);


create table if not exists meeting(
    id bigint primary key  generated by default as identity not null,
    date DATE,
    mark bigint
);

create table if not exists presence(
    id bigint primary key generated by default as identity not null,
    student bigint references student(id),
    date DATE,
    presence varchar(255)
);
create table meeting_to_presence(
    meeting_id bigint references meeting(id),
    presence_id bigint references presence(id)
)

