drop table if exists students cascade;
drop table if exists attendance cascade;
drop table if exists grades cascade;
drop table if exists works cascade;
create table if not exists students
(
    id       bigint primary key generated by default as identity,
    name     varchar(255),
    skype    varchar(255),
    telegram varchar(255),
    github   varchar(255),
    botscore integer,
    isActive varchar(255)
);

-- Занятия
CREATE TABLE works
(
    id        bigint primary key generated by default as identity,
    work_date date not null
);

-- посещаемость
CREATE TABLE attendance
(
    id         bigint primary key generated by default as identity,
    student_id bigint references students (id),
    work_id    bigint references works (id),
    present    varchar not null
);

-- оценки
CREATE TABLE grades
(
    id         bigint primary key generated by default as identity,
    student_id bigint references students (id),
    work_id    bigint references works (id),
    grade      bigint
);
